apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # Slack notification service
  service.slack: |
    token: $slack-token

  # PagerDuty service
  service.pagerduty: |
    token: $pagerduty-token
    from: argocd

  # Notification templates
  template.app-sync-succeeded: |
    message: |
      {{if eq .app.status.operationState.phase "Succeeded"}}:white_check_mark:{{end}} Application *{{.app.metadata.name}}* sync succeeded.
      Revision: {{.app.status.sync.revision}}
      {{if .app.status.operationState.message}}Message: {{.app.status.operationState.message}}{{end}}
    slack:
      attachments: |
        [{
          "color": "#18be52",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Environment", "value": "{{.app.spec.destination.namespace}}", "short": true},
            {"title": "Revision", "value": "{{.app.status.sync.revision | trunc 7}}", "short": true},
            {"title": "Synced At", "value": "{{.app.status.operationState.finishedAt}}", "short": true}
          ]
        }]

  template.app-sync-failed: |
    message: |
      :x: Application *{{.app.metadata.name}}* sync failed!
      Error: {{.app.status.operationState.message}}
    slack:
      attachments: |
        [{
          "color": "#E96D76",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Environment", "value": "{{.app.spec.destination.namespace}}", "short": true},
            {"title": "Error", "value": "{{.app.status.operationState.message}}", "short": false}
          ]
        }]

  template.app-health-degraded: |
    message: |
      :warning: Application *{{.app.metadata.name}}* health is degraded!
    slack:
      attachments: |
        [{
          "color": "#f4c030",
          "fields": [
            {"title": "Application", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Health Status", "value": "{{.app.status.health.status}}", "short": true}
          ]
        }]
    pagerduty:
      title: "NatLangChain Health Degraded"
      body: "Application {{.app.metadata.name}} in {{.app.spec.destination.namespace}} is degraded"

  # Triggers
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-succeeded]

  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]

  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-degraded]

  # Subscriptions (default channels)
  subscriptions: |
    - recipients:
        - slack:natlangchain-deployments
      triggers:
        - on-sync-succeeded
    - recipients:
        - slack:natlangchain-alerts
      triggers:
        - on-sync-failed
        - on-health-degraded
