apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: natlangchain-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: natlangchain-deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: natlangchain-alerts
spec:
  project: natlangchain

  source:
    repoURL: https://github.com/kase1111-hash/NatLangChain.git
    targetRevision: HEAD
    path: charts/natlangchain
    helm:
      releaseName: natlangchain-staging
      valueFiles:
        - ../../argocd/envs/staging/values.yaml
      # Override specific values
      parameters:
        - name: replicaCount
          value: "2"
        - name: autoscaling.minReplicas
          value: "2"
        - name: autoscaling.maxReplicas
          value: "5"

  destination:
    server: https://kubernetes.default.svc
    namespace: natlangchain-staging

  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replica count (managed by HPA)
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /status

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Revision history limit
  revisionHistoryLimit: 10
