apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: natlangchain-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: natlangchain

  source:
    repoURL: https://github.com/kase1111-hash/NatLangChain.git
    targetRevision: HEAD
    path: k8s/monitoring
    # Using Kustomize
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: natlangchain

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # For CRDs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
